apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customerapi
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      containers:
      - name: customerapi
        image: nitrozeus1/customerapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: customerapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: customerapi
  ports:
  - port: 80
    nodePort: 31000