version: '3.4'

services:
  customerapi:
    image: asyno/customerapi/:${DEPLOY_NUMBER}
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile

  orderapi:
    image: asyno/orderapi/:${DEPLOY_NUMBER}
    build:
      context: .
      dockerfile: OrderApi/Dockerfile


  productapi:
    image: asyno/productapi/:${DEPLOY_NUMBER}
    build:
      context: .
      dockerfile: ProductApi/Dockerfile

  reviewapi:
    image: asyno/reviewapi/:${DEPLOY_NUMBER}
    build:
      context: .
      dockerfile: ReviewApi/Dockerfile
  
  apigateway:
    image: asyno/apigateway/:${DEPLOY_NUMBER}
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085

volumes:
  featurehub-h2-data:
    
