version: '3.4'

services:
  customerapi:
    image: asyno/customerapi
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile

  orderapi:
    image: asyno/orderapi
    build:
      context: .
      dockerfile: OrderApi/Dockerfile


  productapi:
    image: asyno/productapi
    build:
      context: .
      dockerfile: ProductApi/Dockerfile

  reviewapi:
    image: asyno/reviewapi
    build:
      context: .
      dockerfile: ReviewApi/Dockerfile
  
  apigateway:
    image: asyno/apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"


  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-network


  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085

volumes:
  featurehub-h2-data:
  jenkins_home:
networks:
  my-network:
    
